/*
 * Todo app OAS
 *
 * OpenApi specification for a todo application
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "GoAPIDevelopment/go"

	"github.com/gorilla/handlers"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	headers := handlers.AllowedHeaders([]string{"X-Requested-With", "Content-Type", "Authorization"})
	methods := handlers.AllowedMethods([]string{"GET", "POST", "PUT", "DELETE"})
	origins := handlers.AllowedOrigins([]string{"http://localhost:8082", "http://localhost:8080"})

	// Add this line to enable CORS
	handler := handlers.CORS(origins, headers, methods)(router)

	log.Fatal(http.ListenAndServe(":8081", handler))
}
