/*
 * Todo app OAS
 *
 * OpenApi specification for a todo application
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"
)

// WIP: Replace Array with DB
var todos []Todo
var domains = [1]string{"development"}

func CreateTodoExternal(w http.ResponseWriter, r *http.Request) {
	var todo Todo

	body, err := ioutil.ReadAll(r.Body)
	if err != nil {
		http.Error(w, "Error reading the Requestbody", http.StatusInternalServerError)
		return
	}

	data := url.Values{}
	// Unmarshal the Byte-Stream into the JSON-Data
	json.Unmarshal(body, &data)
	// WIP: Safe data in todos (e.g.)
	fmt.Println("Der Titel lautet: ", data.Get("title"), 1)

	// time format problems
	conv_completed_at, err := time.Parse("2023-02-20 04:59:12 +0000 +0000", data.Get("completed_at"))
	if err != nil {
		fmt.Println(err)
	}
	todo.CompletedAt = conv_completed_at
	conv_created_at, err := time.Parse("2023-02-20 04:59:12 +0000 +0000", data.Get("created_at"))
	if err != nil {
		fmt.Println(err)
	}
	todo.CreatedAt = conv_created_at
	todo.Title = data.Get("title")
	todo.Description = data.Get("description")
	id_todo, err := strconv.ParseInt(data.Get("id"), 10, 32)
	if err != nil {
		fmt.Println(err)
	}
	todo.Id = int32(id_todo)
	todo.Status = data.Get("status")

	// evtl. schöner machen
	var reporter User
	reporter.Email = data["reporter"][4]
	reporter.Firstname = data["reporter"][0]
	reporter.Role = data["reporter"][1]
	reporter.Surname = data["reporter"][2]
	id_reporter, err := strconv.ParseInt(data["reporter"][3], 10, 32)
	if err != nil {
		fmt.Println(err)
	}
	reporter.Id = int32(id_reporter)
	todo.Reporter = &reporter
	todo.Responsibility = data.Get("responsibility")
	todo.Priority = data.Get("priority")

	todos = append(todos, todo)
	w.WriteHeader(http.StatusCreated)
}

func CreateTodo(w http.ResponseWriter, r *http.Request) {
	todo, err := parseRequest(w, r)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	for _, domain := range domains {
		if todo.Responsibility == domain {
			todos = append(todos, *todo)
			w.Header().Set("Content-Type", "application/json; charset=UTF-8")
			w.WriteHeader(http.StatusOK)
		} else {
			w.Header().Set("Content-Type", "application/json; charset=UTF-8")
			w.WriteHeader(http.StatusForbidden)
		}
	}
}

func DeleteTodo(w http.ResponseWriter, r *http.Request) {
	todo, err := parseRequest(w, r)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	newTodos := []Todo{}

	for _, t := range todos {
		if t.Id != todo.Id {
			newTodos = append(newTodos, t)
			w.Header().Set("Content-Type", "application/json; charset=UTF-8")
			w.WriteHeader(http.StatusOK)
			return
		}
	}

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusNotFound)
}

func GetTodos(w http.ResponseWriter, r *http.Request) {
	json.NewEncoder(w).Encode(todos)
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func GetTodosWithStatus(w http.ResponseWriter, r *http.Request) {
	url := r.URL.Path

	url_split := strings.Split(url, "/")
	status := url_split[3]

	allTodosFromResponsibility := []Todo{}
	for _, t := range todos {
		if t.Responsibility == status {
			allTodosFromResponsibility = append(allTodosFromResponsibility, t)
		}
	}
	fmt.Println(allTodosFromResponsibility)
	json.NewEncoder(w).Encode(allTodosFromResponsibility)
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func UpdateTodo(w http.ResponseWriter, r *http.Request) {
	todo, err := parseRequest(w, r)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	for _, t := range todos {
		if t.Id == todo.Id {
			t.Title = todo.Title
			t.Description = todo.Description
			t.Assignee = todo.Assignee
			t.Status = todo.Status
			t.Priority = todo.Priority

			w.Header().Set("Content-Type", "application/json; charset=UTF-8")
			w.WriteHeader(http.StatusOK)
			return
		}
	}

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusNotFound)
}

func parseRequest(w http.ResponseWriter, r *http.Request) (*Todo, error) {
	var todo Todo
	err := json.NewDecoder(r.Body).Decode(&todo)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return nil, err
	}
	return &todo, nil
}
